### ISSUE TITLE
Quote escaping between 0.0.7 and 0.1.0 causes generated Helm errors

### ISSUE THREAD

**Issue by kjq** [quarkiverse/quarkus-helm#107]
I think something has changed between version 0.0.7 (works) and 0.1.0 (does not work) that might have to do with escaping in the generated Helm chart YAML.  My guess is that is has to do with the below...

In the Quarkus `application.yml` under the Kubernetes annotations:

`alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'`

Renders in the Helm chart:

**0.0.7 - Works**
`alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\": 80}, {\"HTTPS\":443}]"`

**0.1.0 - Does not work, Helm sees it as an invalid string:**
`alb.ingress.kubernetes.io/listen-ports: "[{"HTTP": 80}, {"HTTPS":443}]"`

**Comment by Sgitario** [comment]
This is indeed a regression issue. Thanks for reporting! I've already covered this issue to avoid happening again. 
PR linked.
Will be fixed in the next release 0.1.1 which will be out during this week.
