### ISSUE TITLE
Wrong filename for ArgoCD

### ISSUE THREAD

**Issue by csscriptplus** [quarkiverse/quarkus-helm#110]
My quarkus application created and pushed the helm files to a Nexus Helm repository.
The quarkus archive name is xxxx-helm.tgz
ArgoCD need a filename xxxx.tgz
For me and ArgoCD is "-helm" to much in the filename.
Can I change it over the applications.properties?

**Comment by Sgitario** [comment]
Thanks for reporting this issue!
Actually, I'm thinking of always generating xxxx.tgz unless the user provides a prefix via configuration. Wdyt?

**Comment by csscriptplus** [comment]
For me, that would be the right way to go. Other applications, like ArgoCD, cannot know that a prefix is present.
