### ISSUE TITLE
Allow additional Rancher Charts files in `quarkus.helm.input-directory`

### ISSUE THREAD

**Issue by ThoSap** [quarkiverse/quarkus-helm#116]
Hi,

could you please add the following files ([@ here](https://github.com/quarkiverse/quarkus-helm/blob/0.1.2/deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java#L117-L122)) as valid input files from `quarkus.helm.input-directory`.
These files are additionals for Rancher K8s clusters to enhance the user experience when installing charts ([example screenshot](https://docs.ranchermanager.rancher.io/assets/images/rancher-app-2.6-e804785d84e3d5bbcbce9d059633dce1.png)).
> [Rancher charts are native helm charts with two files that enhance user experience: `app-readme.md` and `questions.yaml`.](https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/helm-charts-in-rancher/create-apps#rancher-charts)

- `app-readme.md` or `app-README.md`
  A file that provides descriptive text in the chart's Rancher UI header.
  Example for `app-readme.md` -> [Longhorn](https://github.com/rancher/charts/tree/dev-v2.7/charts/longhorn/100.2.3%2Bup1.3.2)
  Example for `app-README.md` -> [Official Rancher Monitoring chart](https://github.com/rancher/charts/tree/dev-v2.7/charts/rancher-monitoring/101.0.0%2Bup19.0.3))

- `questions.yml` or `questions.yaml`
  A file that contains questions for a form. These form questions simplify the deployment of a chart. Without it, you must configure the deployment using a values YAML config, which is more difficult.
  Example for `questions.yml` -> [Harvester HCI](https://github.com/rancher/charts/tree/dev-v2.7/charts/harvester-csi-driver/101.0.0%2Bup0.1.14)
 Example for `questions.yaml` -> [VMware vSphere Container Storage Interface](https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-vsphere-csi/2.3.1)

- `requirements.yml` or `requirements.yaml`
  Optional: YAML file listing dependencies for the chart.
  Part of the official Helm v2/v3 spec, consolidated into `Chart.yaml` but is still valid for Helm v3 for existing `requirements.yml/.yaml` -> [Changes Since Helm 2 - Consolidation of requirements.yaml into Chart.yaml](https://helm.sh/docs/faq/changes_since_helm2/#consolidation-of-requirementsyaml-into-chartyaml)

**Comment by Sgitario** [comment]
Thanks for reporting and the really helpful explanation! 
I've already submitted a pull request including these changes.

**Comment by ThoSap** [comment]
Nothing related to this issue, but as in my opinion this Quarkus extension is totally underrated and deserves a own Quarkus blog post like for example Quinoa 🙌🏼

**Comment by Sgitario** [comment]
Many thanks for your kind words! Indeed, I should update this post to include the latest features like the support of templates and complex Helm expressions.
