### ISSUE TITLE
Quarkus native build corrupt

### ISSUE THREAD

**Issue by csscriptplus** [quarkiverse/quarkus-helm#121]
Generally Helm chart works only until Quarkus version 2.13.2. A normal docker image build with jib and helm charts works. The docker image is uploaded to registry. But when I start a native build (-Pnative) then can helm upload the chart's archive but jib can't upload the docker image. I get a HTTP 403 exception.
[2.13.2_helm.txt](https://github.com/quarkiverse/quarkus-helm/files/9889196/2.13.2_helm.txt)
[2.13.2_native_helm.txt](https://github.com/quarkiverse/quarkus-helm/files/9889201/2.13.2_native_helm.txt)

**Comment by Sgitario** [comment]
Hi @csscriptplus , I could not reproduce this issue either using Quarkus 2.13.2 or a newer version. 
Yet looking at the logs you provided, this seems to be an issue with the Quarkus Container Image Jib extension, not Quarkus Helm. Please, report it at https://github.com/quarkusio/quarkus/issues and perhaps provide a reproducer too.
