### ISSUE TITLE
quarkus.helm.dependencies.0.wait-for-service-only-command-template configuration problem

### ISSUE THREAD

**Issue by csscriptplus** [quarkiverse/quarkus-helm#122]
**In the documentation is this part defined:**

> This configuration will add the following init-containers in the Deployment resource of your Quarkus application:
> 
> src/main/helm/kubernetes/templates/deployment.yaml:
> 
> initContainers:
> - image: alpine:3.16.2
>   args:
>   - -c
>   - for i in $(seq 1 200); do nc -z -w3 chart-database && exit 0 || sleep 3; done; exit 1
>   command:
>   - sh

**For the kubernetes.yaml I defined this:**
```
- quarkus.kubernetes.init-containers."init-containers".image=curlimages/curl:latest
- quarkus.kubernetes.init-containers."init-containers".command=sh
- quarkus.kubernetes.init-containers."init-containers".arguments=-c, while [ $(curl -sw '%{http_code}' http://nexus.demmtop.local -o /dev/null) -ne 200 ]; do sleep 2; done
```
**And now I want it in my helm chart. I added this:**

```
- quarkus.helm.dependencies.0.image=curlimages/curl:latest
- quarkus.helm.dependencies.0.command=sh
- quarkus.helm.dependencies.0.wait-for-service-only-command-template=-c, while [ $(curl -sw '%{http_code}' http://nexus.development -o /dev/null) -ne 200 ]; do sleep 2; done
```
But according to the error message I need quarkus.helm.dependencies.0.repository and quarkus.helm.dependencies.0.version.
Why that? How is the configuration correct?

**Comment by Sgitario** [comment]
If you want to define your own "init-containers" container definition, you don't need to do anything special for helm charts. I mean that if you keep the following configuration:

```
quarkus.kubernetes.init-containers."init-containers".image=curlimages/curl:latest <1>
quarkus.kubernetes.init-containers."init-containers".command=sh
quarkus.kubernetes.init-containers."init-containers".arguments=-c, while [ $(curl -sw '%{http_code}' http://nexus.demmtop.local -o /dev/null) -ne 200 ]; do sleep 2; done <2>
```

It will work for the Helm chart as well. 

The property "wait-for-service" in the Helm dependencies is a String value that stands for <kubernetes service name>:<kubernetes service port>. If you add this property, then you don't need the above `quarkus.kubernetes.init-containers...` properties, but simply `quarkus.helm.dependencies.0.wait-for-service=chart-database:5432`. Having this latter property will make this extension automatically add an init container to the Deployment resource. 

Additionally, you can change the image in <1> of this auto-generated init container using the property `quarkus.helm.dependencies.0.wait-for-service-image=alpine:3.16.2` (by default, it's `busybox:1.34.1`). And the same for the the arguments <2> using the property `quarkus.helm.dependencies.0.wait-for-service-port-command-template`. However, I would say you don't need to change these two properties unless you really know what you're doing. 

Let me know if you have further questions and I'm here happy to help :)

**Comment by csscriptplus** [comment]
Thanks for the help. It is correct that the kubernetes.init-container statements also work for helm charts.
My problem was that my pod stopped at the "init container". So I thought that the configuration does not work for helm charts.
But it was an error in the "command" command. I took the Nexus DNS pod name. And forgot that Nexus itself does not run on port 80. In my old configurations I had taken the Ingress name. Ingress maps the ports.
Sorry, my mistake.

**Comment by Sgitario** [comment]
Glad you sorted it out!
