### ISSUE TITLE
Helm charts not upgradable

### ISSUE THREAD

**Issue by csscriptplus** [quarkiverse/quarkus-helm#128]
The spec.selector in the deployment.yaml contains the "app.kubernetes.io/version".
**Kubernetes says:**
> Note: In API version apps/v1, a Deployment's label selector is immutable after it gets created.

The problem is that with each new version the label "app.kubernetes.io/version" changes. And then Helm upgrade does not work anymore.
"app.kubernetes.io/version" must be removed in spec.selector.

**Comment by Sgitario** [comment]
Hello @csscriptplus , you can configure the Quarkus Kubernetes extension to not create the version label by adding `quarkus.kubernetes.add-version-to-label-selectors=false` in your configuration.

**Comment by csscriptplus** [comment]
@Sgitario thanks. It works.
