### ISSUE TITLE
The name property in HelmDependencyConfig should be optional

### ISSUE THREAD

**Issue by iocanel** [quarkiverse/quarkus-helm#130]
Refering to this:
https://github.com/quarkiverse/quarkus-helm/blob/main/deployment/src/main/java/io/quarkiverse/helm/deployment/HelmDependencyConfig.java#L15

If the name is not explictly specified the key of containing map entry should be used.
This would allow for one line configuration like.
It would also make the key meaningful, which right now is just ignored.

This is a pattern that I think we have already employed in some areas around kubernetes, kubernetes-service-binding etc.

**Comment by Sgitario** [comment]
This makes totally sense. Will work on this asap.
