### ISSUE TITLE
Add property quarkus.helm.values.[0].value-as-map

### ISSUE THREAD

**Issue by jtvmatos** [quarkiverse/quarkus-helm#134]
With the addition of the `Helm Expressions Support`, It would be useful a `quarkus.helm.values.[0].value-as-map` to provide arguments for range functions.

Something like:
```
quarkus.helm.values.1.property=my_custom_labels
quarkus.helm.values.1.paths=(kind == Deployment).metadata.labels
quarkus.helm.values.1.expression={{ include "my_custom_merge_function" . | indent 2 }}
#quarkus.helm.expressions.1.expression={{- range $key, $val := .Values.favorite }}\n\
#{{ indent 2 $key }}: {{ $val | quote }}\n\
#{{- end }}
quarkus.helm.values.1.value-as-map={"key1": "value1", "key2": "value2"}
``` 
Thanks.

**Comment by Sgitario** [comment]
Many thanks for reporting!
This pull request implements this feature: https://github.com/quarkiverse/quarkus-helm/pull/140
Note that the right format to express a map in Quarkus is:
```
quarkus.helm.values.1.value-as-map.key1=value1
quarkus.helm.values.1.value-as-map.key2=value2
```

**Comment by jtvmatos** [comment]
Hi @Sgitario,
Thanks for the quick response and feature added!

With this feature will be possible to specify an empty map as default? Something like
```
app:
   extraLabels: [ ]
```

thanks!

**Comment by Sgitario** [comment]
> With this feature will be possible to specify an empty map as default? 

Unfortunately, this is not supported yet using properties, though you can provide your custom values.yaml file in `src/main/helm/values.yaml` with:
```yaml
app:
   extraLabels: { }
```

And this values.yaml will be integrated with the generated one by this extension.
