### ISSUE TITLE
Add root level conditions

### ISSUE THREAD

**Issue by jtvmatos** [quarkiverse/quarkus-helm#137]
Depending on the environment it may be necessary to disable the creation of some resources (e.g., ingress, PVC's, etc).
It would be very useful to be able to pass conditional functions in the root of the resource template, to achieve something like:
```
{{- if .Values.app.ingress.enabled }}
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
...
{{- end }}
```
Not so critical, at least for me, is adding conditions to specific inputs inside the template, for example:
```
...
    {{- if .Values.app.ingress.tls.enabled }}
        tls:
            - hosts:
    {{- end }}
...
```
I'm not sure of the best way to implement it, but maybe adding a `quarkus.helm.expressions.1.pathHeader` and a `quarkus.helm.expressions.1.pathFooter`, WDYT?

Thanks.

**Comment by Sgitario** [comment]
> Depending on the environment it may be necessary to disable the creation of some resources (e.g., ingress, PVC's, etc). It would be very useful to be able to pass conditional functions in the root of the resource template, to achieve something like:
> 
> ```
> {{- if .Values.app.ingress.enabled }}
>   apiVersion: networking.k8s.io/v1
>   kind: Ingress
>   metadata:
>     annotations:
> ...
> {{- end }}
> ```
> 
> Not so critical, at least for me, is adding conditions to specific inputs inside the template, for example:
> 
> ```
> ...
>     {{- if .Values.app.ingress.tls.enabled }}
>         tls:
>             - hosts:
>     {{- end }}
> ...
> ```
> 
> I'm not sure of the best way to implement it, but maybe adding a `quarkus.helm.expressions.1.pathHeader` and a `quarkus.helm.expressions.1.pathFooter`, WDYT?
> 
> Thanks.

Unfortunately, this is harder to support than at first glance looks. 
Also, you can already do this using templates, see https://quarkiverse.github.io/quarkiverse-docs/quarkus-helm/dev/index.html#_helm_expressions_support. You need to create a template that adds the TLS configuration of an ingress according to the property you specify. 

Though, let's keep this issue open, so other users can request an easier way to configure conditional properties/resources.

**Comment by jtvmatos** [comment]
Hi @Sgitario,

First of all, thanks for the feedback!

Regarding the second scenario, for conditions inside the template, it will be hard to use helm expressions. For instance, if I specify these conditions:
```
quarkus.helm.expressions.1.path=(kind == Ingress).spec
quarkus.helm.expressions.1.expression=\n  {{- if .Values.app.ingress.tls.enabled }}\n  tls: \n    - hosts:\n  {{- end }}
```
all the `spec` array will be rewritten. To use helm expressions, I need to manually add all the items from the `spec` to the expression. Moreover, all the new `quarkus.kubernetes.ingress.` configurations changes will be ignored.


Nevertheless, for the first scenario (root level conditions) this solution will not work. At least for now, something like this don't work:
```
quarkus.helm.expressions.0.path=(kind == Ingress && metadata.name == api-ingress)
quarkus.helm.expressions.0.expression={{- if .Values.app.ingress.enabled }}\n apiVersion: networking.k8s.io/v1\n kind: Ingress \n metadata: ........ {{- end }}
```

Any other suggestions as workaround?

**Comment by Sgitario** [comment]
No, you should provide your custom template, you can find an example in https://github.com/quarkiverse/quarkus-helm/tree/main/integration-tests/helm-kubernetes-with-templates.
This example adds this template: https://github.com/quarkiverse/quarkus-helm/blob/main/integration-tests/helm-kubernetes-with-templates/src/main/helm/templates/_helpers.tpl

Inside the template, you can add the if statement to modify/add the Ingress resource.

And next, you can use this template as https://github.com/quarkiverse/quarkus-helm/blob/edcf6fcba3d8bc7d718c8bc40af288b19ee0d442/integration-tests/helm-kubernetes-with-templates/src/main/resources/application.properties#L5. 

You would need to provide the right path.

**Comment by Sgitario** [comment]
> 

I understand the problems you state. 
I'm planning to take a look into this today and see if there is something we can do to easier this use case.

**Comment by Sgitario** [comment]
@jtvmatos I've partially implemented this feature but only at the resource level in https://github.com/quarkiverse/quarkus-helm/pull/146.
As I imagined, doing this also at the path level is very much harder to implement.
