### ISSUE TITLE
Document OpenShift specifics

### ISSUE THREAD

**Issue by rsvoboda** [quarkiverse/quarkus-helm#147]
https://quarkiverse.github.io/quarkiverse-docs/quarkus-helm/dev/index.html is covering setup against vanilla Kubernetes.

Please document OpenShift specifics.

I was able to run the quickstart against OpenShift instance with following differences:

 - `quarkus-openshift` instead of `quarkus-kubernetes` extension
 - `helm install helm-quickstart ./target/helm/openshift/helm-quickstart` instead of `./target/helm/kubernetes`
 - application.properties with:
```properties
quarkus.openshift.route.expose=true
quarkus.container-image.builder=docker
```

**Comment by Sgitario** [comment]
It's done by https://github.com/quarkiverse/quarkus-helm/pull/150.
I've also refactored the documentation to improve the navigation.
Thanks for reporting!
