### ISSUE TITLE
Support to Kubernetes Custom Resource Definition (CRDs)

### ISSUE THREAD

**Issue by jtvmatos** [quarkiverse/quarkus-helm#174]
Hi, 

According the Oficial Helm documentation, helm charts support a CRDs folder: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

It is possible to have this folder to add the CRDs Generated by Fabric8/quarkus-operator-sdk? Or at least can be added to the `quarkus.helm.input-directory` to manually add CRDs?

Thanks!

**Comment by Sgitario** [comment]
Let's include the resources in `crds` folder to the generated chart: https://github.com/quarkiverse/quarkus-helm/pull/175
