### ISSUE TITLE
Potential regression from 0.2.5 to 0.2.6 with label processing

### ISSUE THREAD

**Issue by ingmarfjolla** [quarkiverse/quarkus-helm#182]
Hello, I'm not sure if perhaps something changed that requires extra configuration, but it seems that upgrading to 0.2.6 changes the way that labels/flags are processed. Working on [this](https://github.com/quarkusio/quarkus-super-heroes/issues/130) issue for Quarkus Superheroes, I'm seeing different output in my values yaml and what gets placed in the templates as well. I attached some pictures to make it easier to show what I'm talking about. The command that's being run when building the app is: 

```
/mvnw -f $project/pom.xml versions:set clean package \
    -DskipTests \
    -DnewVersion=$container_tag \
    -Dmaven.compiler.release=$javaVersion \
    -Dquarkus.container-image.tag=$container_tag \
    -Dquarkus.kubernetes.deployment-target=$deployment_type \
    -Dquarkus.kubernetes.version=$container_tag \
    -Dquarkus.kubernetes.ingress.expose=$expose \
    -Dquarkus.kubernetes.resources.limits.memory=$mem_limit \
    -Dquarkus.kubernetes.resources.requests.memory=$mem_request \
    -Dquarkus.kubernetes.annotations.\"app.quarkus.io/vcs-url\"=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
    -Dquarkus.kubernetes.annotations.\"app.quarkus.io/vcs-ref\"=$github_ref_name \
    -Dquarkus.openshift.version=$container_tag \
    -Dquarkus.openshift.route.expose=$expose \
    -Dquarkus.openshift.resources.limits.memory=$mem_limit \
    -Dquarkus.openshift.resources.requests.memory=$mem_request \
    -Dquarkus.openshift.annotations.\"app.openshift.io/vcs-url\"=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
    -Dquarkus.openshift.annotations.\"app.openshift.io/vcs-ref\"=$github_ref_name \
    -Dquarkus.knative.version=$container_tag \
    -Dquarkus.knative.labels.\"app.openshift.io/runtime\"=quarkus \
    -Dquarkus.knative.resources.limits.memory=$mem_limit \
    -Dquarkus.knative.resources.requests.memory=$mem_request \
    -Dquarkus.knative.annotations.\"app.openshift.io/vcs-url\"=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
    -Dquarkus.knative.annotations.\"app.openshift.io/vcs-ref\"=$github_ref_name
```
the ones with the extra values that are empty are with 0.2.6. 

![Screenshot from 2023-02-20 12-05-51](https://user-images.githubusercontent.com/33461904/220166440-abd7367f-ffc8-4064-9984-42d67cea871a.png)
![Screenshot from 2023-02-20 12-05-42](https://user-images.githubusercontent.com/33461904/220166443-5c6244c8-ffee-4491-8c65-b9a53b171859.png)
![Screenshot from 2023-02-20 11-52-10](https://user-images.githubusercontent.com/33461904/220166445-80714c68-86ab-4523-9d4e-a160e2d32d11.png)
![Screenshot from 2023-02-20 11-51-58](https://user-images.githubusercontent.com/33461904/220166447-180106d2-37c6-4058-b4ca-48225e0f45cf.png)

**Comment by Sgitario** [comment]
This is because we're exposing all the system properties you use as params, so you can change it when installing the chart. 
Though, are the empty properties causing failures when installing the chart? Otherwise, I don't see it as a potential regression. You can always disable this feature by adding the property: `quarkus.helm.map-system-properties=false`. 

Moreover, I will make a change to ignore the `quarkus.kubernetes.xxx` properties.
