### ISSUE TITLE
Convert Uppercase value separated with underscore to lower & camel case values 

### ISSUE THREAD

**Issue by cmoulliard** [quarkiverse/quarkus-helm#203]
## Suggestion

Convert the uppercase value separated with underscore such as `QUARKUS_DATASOURCE_NAME` to lower & camel case values:
```
quarkusDatabaseName
or
quarkus: 
   database:
      name:
```

**Comment by Sgitario** [comment]
what is the value or the use case? 
At the moment, this is up to the users to use either `QUARKUS_DATASOURCE_NAME` or `quarkusDatabaseName`,

**Comment by cmoulliard** [comment]
> what is the value or the use case?

I was thinking that declaring the properties using Uppercase and underscore was needed for the quarkus application or kubernetes generator. 

If we can use:
```
quarkus.vault.url=${vaultUrl:vault.127.0.0.1.nip.io}
```

instead of 
```
quarkus.vault.url=${VAULT_URL:vault.127.0.0.1.nip.io}
```

then I'm fine.

**Remark**: We should perhaps offer the possibility to convert a camelCase property to its yaml equivalent such
```
quarkus.vault.url=${vaultUrl:vault.127.0.0.1.nip.io}
-->
vault:
  url
```

**Comment by Sgitario** [comment]
Yes, you can use any of the options: `${vaultUrl:vault.127.0.0.1.nip.io}` or `${VAULT_URL:vault.127.0.0.1.nip.io}`.
Moreover, if you use: `${vault.url:vault.127.0.0.1.nip.io}`, you will see what you wanted:

```yaml
app:
  envs:
    vault:
      url: vault.127.0.0.1.nip.io
```

Note that these properties are added at `app.envs`. This is something we can't change atm.

**Comment by cmoulliard** [comment]
> Note that these properties are added at `app.envs`. This is something we can't change atm.

This is logic as such properties are used as env var by the application.

As the features I was reporting exist, I propose to close the ticket at the condition that this is also well documented with examples and why not some best practices ;-)
