### ISSUE TITLE
Your solution to Issue #208 is problematic

### ISSUE THREAD

**Issue by wgresshoff** [quarkiverse/quarkus-helm#218]
Sorry, just forbidding the usage of "-" in properties is very problematic. Some properties in K8s manifests (like `ephemeral-storage`) contains this char and can't be set any more.
Our K8s cluster expects it's defined.

**Comment by Sgitario** [comment]
Having these characters cause the Helm chart installation to fail with, for example:

```
helm install --dependency-update fruits-app target/helm/kubernetes/fruits-app
Error: INSTALLATION FAILED: parse error at (fruits-app/templates/servicebinding.yaml:1): bad character U+002D '-'
```

How these characters can cause installation issues and on the other hand, be mandatory in other scenarios?

**Comment by wgresshoff** [comment]
I think this is a different use case: I want to define a property in a kubernetes manifest (which is run by kubectl) but the installation issue arises in a part which is interpreted by helm (or Go).
I'm using something like
```
quarkus.helm.values.5.property=postgresql.primary.resources.limits.ephemeral-storage
quarkus.helm.values.5.value=500Mi
```
to populate my `values.yaml`, the so generated part is just copied over by my helm template but neither parsed nor interpreted.
Perhaps it would be sufficient to allow values of properties with a dash if they are defined under
```
quarkus.helm.value...
```

**Comment by wgresshoff** [comment]
Sorry, I wasn't aware of this possibility! Thanks for your help and your patience!

**Comment by Sgitario** [comment]
Glad it helped!
