### ISSUE TITLE
Incorrect instructions to deploy to OpenShift

### ISSUE THREAD

**Issue by yrodiere** [quarkiverse/quarkus-helm#316]
See here: https://docs.quarkiverse.io/quarkus-helm/dev/index.html#usage-helm-openshift

This tells us to push the image to OpenShift, and *then* deploy Helm charts.

But from what I can see, this won't work on a clean namespace, because pushing the image to OpenShift will auto-create an ImageStream without any annotation, and Helm will refuse to install charts if an ImageStream from the chart already exists and doesn't have a `...managed-by=Helm` annotation.

The only way I managed to make this all work was to build the image, then deploy the charts, then push the image.

I'm using `jib` to build the container image rather than `docker`, but I don't think that matters?

**Comment by yrodiere** [comment]
Apparently I did something wrong, because when I'm tring to do this now, there's no ImageStream template in the helm chart. So there is no problem creating the image stream manually (well, there's the problem of local image resolution, but that's different).

Closing, sorry for the noise.

**Comment by Sgitario** [comment]
Many thanks for looking into it @yrodiere !
