### ISSUE TITLE
Support Quarkus profiles

### ISSUE THREAD

**Issue by pjgg** [quarkiverse/quarkus-helm#32]
By default a Quarkus application support three applications [profiles](https://quarkus.io/guides/config-reference#profiles): `dev`, `test` and `prod` . As a developer, I would like that any profile (even a custom profile) could be translated into a separate Helm chart `values.yaml`. 

For example: 

Application.properties
```
# Application properties
quarkus.openshift.expose=true
quarkus.openshift.route.expose=true

quarkus.kubernetes.expose=true
quarkus.kubernetes.ingress.expose=true

quarkus.container-image.image=quay.io/quarkusqeteam/examples-quarkus-helm:1.2.1.Beta1-SNAPSHOT
%prod.quarkus.container-image.image=quay.io/quarkusqeteam/examples-quarkus-helm:1.2.1

quarkus.kubernetes.host=examples-quarkus-helm.apps.ocp4-10.dynamic.quarkus
%prod.quarkus.kubernetes.host=examples-quarkus-helm.prod.apps.ocp4-10.dynamic.quarkus

quarkus.container-image.builder=docker
```

My proposal is generate one Helm chart `values.yaml` per profile

- values.yaml -> default configuration
```
examplesQuarkusHelm:
  image: quay.io/quarkusqeteam/examples-quarkus-helm:1.2.1.Beta1-SNAPSHOT
  host: examples-quarkus-helm.apps.ocp4-10.dynamic.quarkus
```
- prod-values.yaml -> prod configuration
```
examplesQuarkusHelm:
  image: quay.io/quarkusqeteam/examples-quarkus-helm:1.2.1
  host: examples-quarkus-helm.prod.apps.ocp4-10.dynamic.quarkus
```

All common properties would be in both values.yaml

To install one helm chart or other you will just apply the `values.yaml` that match with your environment

`helm install -f prod-values.yaml`

**Comment by Sgitario** [comment]
Quarkus profiles stand for a very different concept than Helm profiles, and I don't think we should mix up both things. 
We can use the Helm profiles with the exact behavior you're expecting: https://quarkiverse.github.io/quarkiverse-docs/quarkus-helm/dev/index.html#_helm_profiles
