### ISSUE TITLE
mapSystemProperties ignores YamlConfigSource  

### ISSUE THREAD

**Issue by mapuci** [quarkiverse/quarkus-helm#367]
reproducer: https://github.com/mapuci/helm-config-yam/tree/main

Summary: If using `quarkus-config-yaml` extension, properties defined in `*.yml` or `*.yaml` do not get mapped to helm's values.yaml file.

**Comment by mapuci** [comment]
https://github.com/quarkiverse/quarkus-helm/pull/368

**Comment by mapuci** [comment]
https://github.com/quarkiverse/quarkus-helm/issues/335 is probably a duplicate issue, I will check it once this one gets resolved.

**Comment by Sgitario** [comment]
Fixed by https://github.com/quarkiverse/quarkus-helm/pull/368. 
Thanks @mapuci !
