### ISSUE TITLE
mapSystemProperties maps unwanted 'property expression' properties

### ISSUE THREAD

**Issue by mapuci** [quarkiverse/quarkus-helm#369]
Lets say I have 2 lines in application.properties
```
property1=${ENV_VARIABLE1:defaultValue}
property2=${quarkus.application.name}-someSuffix
```

- The first is actual env variable, and it must be (and it is) mapped inside `values.yaml`.
- The second one is just `property expression` using some existing property, changing it a bit. But `quarkus.application.name` is mapped to `values.yaml` despite it being existing quarkus variable, and I am only using it. 

Reproducer: https://github.com/mapuci/helm-config-yam/tree/main

I believe that makes no sense. Every expression `${...}` is used as env variable. 

<img width="1309" alt="image" src="https://github.com/user-attachments/assets/05993cbf-f69d-41d6-8e6c-1929ed915bf2">

I suggest we create new property `quarkus.helm.map-system-properties-format` (e.g. `UPPERCASE_UNDERSCORE`) that will filter out unwanted properties.

**Comment by mapuci** [comment]
@Sgitario could you point me to the right direction here... I will gladly do the coding part :)

**Comment by Sgitario** [comment]
> @Sgitario could you point me to the right direction here... I will gladly do the coding part :)

I don't want to overcomplicate this logic or add any more properties related to this since the name convention of the variables is opinionated. Plus, users can always disable this mapping and use the standard way to map env-vars as stated in https://quarkus.io/guides/deploying-to-kubernetes#env-vars
