### ISSUE TITLE
Values are not being mapped anymore

### ISSUE THREAD

**Issue by kjq** [quarkiverse/quarkus-helm#44]
This is a great extension and is invaluable in our process!

But, upgrading to v0.0.3 I get multiple issues with the value mappings. Downgrading to v0.0.2 does not help.  This was working at one point fine. If I downgrade to v0.0.2 the extension and downgrade Quarkus to 2.10.3 it works.

We are using the latest Quarkus version `2.11.2.Final` with the Kubernetes and YAML configuration extensions.

- Using `json-paths` only `image` and other container properties (looks to be anything with the `app.` prefix) are mapped to the values.yml
```
    "values":
        "0":
            property: branch
            json-paths: $..metadata.labels['io.company/branch']
            value: ${CHART_BRANCH:main}
```

- Using `paths` and exception is thrown `SRCFG00014: The config property quarkus.helm.values.6.json-paths is required but it could not be found in any config source`
```
     "values":
        "6":
            property: new-branch
            paths: metadata.name
            value: ${CHART_BRANCH:main}
```

**Comment by Sgitario** [comment]
Thanks for your feedback!

About this issue, I fixed this issue yesterday, but haven't released it until today. Please, try the new version [0.0.4](https://github.com/quarkiverse/quarkus-helm/releases/tag/0.0.4) out.

The right expression should be: `paths=metadata.labels.'io.company/branch'`. From version 0.0.3, we are not using JSONPath expressions any longer, but YAMLPath expressions: https://github.com/yaml-path/YamlPath.

You can find more examples here: https://github.com/quarkiverse/quarkus-helm/blob/13ccddb64aefa82e86d01101bbf064cbb02d1506/integration-tests/helm-kubernetes-full/src/main/resources/application.properties#L26

Please, let me know if using 0.0.4 is working for you!

**Comment by kjq** [comment]
Works like a charm!  Thanks for the quick turn around.  This extension plays a very important role in our architecture and it is super useful.

**Comment by Sgitario** [comment]
Many thanks for the feedback!
