### ISSUE TITLE
K8s `quarkus.kubernetes.expose` is ignored in favor to `quarkus.kubernetes.ingress.expose`

### ISSUE THREAD

**Issue by pjgg** [quarkiverse/quarkus-helm#47]
Deprecated `quarkus.kubernetes.expose` is not implemented, is this decision intended? 

Also `quarkus.openshift.expose` is ignored in favor to `quarkus.openshift.route.expose`

**Comment by Sgitario** [comment]
Yes, that was intentional. By the way, this kind of question should be posted in https://github.com/quarkusio/quarkus, and perhaps not as an issue, but as a discussion topic.
