### ISSUE TITLE
Output directory is now always inside target

### ISSUE THREAD

**Issue by antssilva96** [quarkiverse/quarkus-helm#58]
From 0.0.4 to 0.0.5 the resolution of the output target was changed:
![image](https://user-images.githubusercontent.com/84567479/187938139-390660c4-b796-4ffc-b25d-8dc7f0539f6d.png)

I can add a property to make this optional if you want but I'm unsure if this has any side effects.

**Comment by Sgitario** [comment]
Sorry for this change not being notice in the release notes :/

We already have the property `quarkus.helm.output-directory` to configure this. This property is relative to the target directory (which is also configurable in Quarkus using the property `quarkus.package.output-directory`).  So, you can add the property `quarkus.helm.output-directory=../otherFolder`, and the Helm resources will be generated in the parent of the target directory. 

I will improve the documentation of this property and also allow using absolute paths.
