### ISSUE TITLE
helm link gives ERROR about chart api version

### ISSUE THREAD

**Issue by antssilva96** [quarkiverse/quarkus-helm#61]
I see in the code that QuarkusHelmWriterSessionListener has a constant with 
`private static final String CHART_API_VERSION = "v1";`

However this gives the following error when running `helm lint`
![image](https://user-images.githubusercontent.com/84567479/187945811-3bdda926-44e5-4cde-bbc3-e0893a526309.png)

Not sure if this can be updated or should be parametrized..

**Comment by Sgitario** [comment]
This should be indeed configurable. The fix will be included in the next release. Thanks for reporting!
