### ISSUE TITLE
Image is wrong in values.yaml

### ISSUE THREAD

**Issue by antssilva96** [quarkiverse/quarkus-helm#62]
The image in values.yaml is using the default values described in https://quarkus.io/guides/container-image#container-image-options 
![image](https://user-images.githubusercontent.com/84567479/187962592-91232286-ad71-4df0-bd6f-8078914cad03.png)

If we compare with the generated kubernetes.yaml, it uses the correct values provided via 

```
quarkus.container-image.registry
quarkus.container-image.group
```

Expected: `image: docker.my-internal-registry.com/my-group/project-name:1.0.0-SNAPSHOT`
Current: `image: antonio.silva/project-name:1.0.0-SNAPSHOT`

The container-image.name is working as expected but the registry and group are not being considered.

**Comment by Sgitario** [comment]
Thanks for reporting! I will investigate it further and provide a fix in Quarkus upstream.

**Comment by Sgitario** [comment]
I think this issue is duplicated with https://github.com/quarkiverse/quarkus-helm/issues/41. If not, please feel free to reopen it.
