### ISSUE TITLE
Allow a condition to be provided to helm dependencies

### ISSUE THREAD

**Issue by antssilva96** [quarkiverse/quarkus-helm#67]
On Chart v2 (related to #65) it is possible to define conditions on helm dependencies (See [this stackoverflow question](https://stackoverflow.com/questions/54032974/helm-conditionally-install-subchart))

My idea was to add a `condition`  optional to `HelmDependencyConfig` and add a `validateHelmConfig` method in the `HelmProcessor` that fails if the optional is non empty and the api version is 1.

However, I checked the quarkus-helm code and this seems to be a limitation coming from dekorate itself.

**Comment by Sgitario** [comment]
Yep, indeed this needs to be addressed in Dekorate first.

**Comment by Sgitario** [comment]
Fix in Dekorate upstream: https://github.com/dekorateio/dekorate/pull/1052
Will mark as resolved once this pull request is merged, Dekorate released and Quarkus bumped to this Dekorate version.
