### ISSUE TITLE
Add property to allow passing a helm chart readme file

### ISSUE THREAD

**Issue by antssilva96** [quarkiverse/quarkus-helm#69]
When the helm chart is deployed to harbor it has a summary page displays the contents of the helm chart readme.

More info in https://helm.sh/docs/topics/charts/#chart-license-readme-and-notes

**Comment by Sgitario** [comment]
Can you provide more information, please?

**Comment by Sgitario** [comment]
I think this is already covered as part of the changes in https://github.com/quarkiverse/quarkus-helm/pull/72.
If not, feel free to reopen this issue.
