### ISSUE TITLE
Bug deleting output folder

### ISSUE THREAD

**Issue by antssilva96** [quarkiverse/quarkus-helm#77]
On the line `deleteOutputHelmFolderIfExists(outputFolder);`

we're doing ` FileUtil.deleteIfExists(outputFolder.resolve(FEATURE));`

where `FEATURE` is `helm`.

The thing is that the output folder default is already `helm` so we are actually deleting `helm/helm`.

**Comment by Sgitario** [comment]
Thanks for reporting. This should be fixed in the linked pull request.
