### ISSUE TITLE
Api version keeps generating as v1

### ISSUE THREAD

**Issue by tobiasvdp** [quarkiverse/quarkus-helm#86]
Tried to set to v2 manually, but just not changing at all.
![image](https://user-images.githubusercontent.com/5156314/190872975-53ef31be-185b-41b5-9d2a-2eab65d62ade.png)

result
![image](https://user-images.githubusercontent.com/5156314/190872993-0031a223-8262-4d53-87cc-f30accbcfd81.png)

Also notices the upload to repo isnt working, but might be blocked by above function

Nothing really special about this setup
With deps
![image](https://user-images.githubusercontent.com/5156314/190873030-0e42b93b-f76a-434d-b2e7-d9611ba19d51.png)

Running quarkus <quarkus.platform.version>2.11.3.Final</quarkus.platform.version>

Kind regards
Tobias

**Comment by Sgitario** [comment]
This is because this change has not been released yet, spites the documentation is updated with `main` (unreleased version). I'm trying to figure out how to avoid this in the future.
